# Updated _config.yml - Fix for underscore directories

title: "ATT4CKQL"
description: "Enhanced KQL Queries for Microsoft Sentinel based on MITRE ATT&CK Techniques"
baseurl: "" 
url: "https://realnamesareboring.github.io/ATT4CKQL/"

markdown: kramdown
highlighter: rouge

# Keep existing collections for platforms only
collections:
  platforms:
    output: true
    permalink: /platforms/:name/

defaults:
  - scope:
      path: ""
      type: "platforms"
    values:
      layout: "platform"

plugins:
  - jekyll-feed
  - jekyll-sitemap

# UPDATED: Include renamed directories (without underscores)
include:
  - "Amazon Web Services"
  - "Amazon Web Services/logs"
  - "Amazon Web Services/explained"  
  - "Amazon Web Services/Queries"
  - "Azure"  
  - "Azure/logs"
  - "Azure/explained"
  - "Azure/Queries"
  - "GCP"
  - "GCP/logs"
  - "GCP/explained"
  - "GCP/Queries"
  - "Active Directory"
  - "Microsoft 365"
  - "Entra ID"

exclude:
  - Gemfile
  - Gemfile.lock